### ISSUE TITLE
Garys gif cannot be found 

### ISSUE THREAD

**Issue by mgely** [steelelab-delft/stlab#41]
When cloning the repo and trying to initiate an instrument without resetting, the following error occurs:

couldn't open "C:\libs\stlab\utils\Gary-Steele-web.gif": no such file or directory

The gif is currently not in a location in the repo

**Comment by feschmidt** [comment]
The gif is on every single branch except for TimeDomain. A possible cause for the error might be that your absolute path is different from the default one. The gif will only appear if you clone to `C:\libs\stlab\`. Maybe we can change this to the relative path.
Note that if you clone to anything other than `C:\libs`, the steelelab-getgitid routine will probably run into the same issue...
https://github.com/steelelab-delft/stlab/blob/3e97947237d5303f3887e953e518d5dfcbccd6a7/utils/getgitid.py#L34-L37
We should probably get the relative stlab path instead...

![image](https://user-images.githubusercontent.com/21104656/57016667-ad5d4b00-6c1b-11e9-98fd-6606002e5049.png)
![image](https://user-images.githubusercontent.com/21104656/57016673-b9490d00-6c1b-11e9-82a9-d1f2826cf4b2.png)
![image](https://user-images.githubusercontent.com/21104656/57016689-c49c3880-6c1b-11e9-8190-6ecf38838f43.png)

**Comment by feschmidt** [comment]
closed for now because all measurement PCs are set up in the same way
